/*
Deployment script for CompanyInformationContext-183e4640-bb9f-4f9b-8824-992636816964

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "CompanyInformationContext-183e4640-bb9f-4f9b-8824-992636816964"
:setvar DefaultFilePrefix "CompanyInformationContext-183e4640-bb9f-4f9b-8824-992636816964"
:setvar DefaultDataPath "%localappdata%\Microsoft\Microsoft SQL Server Local DB\Instances\ProjectModels\"
:setvar DefaultLogPath "%localappdata%\Microsoft\Microsoft SQL Server Local DB\Instances\ProjectModels\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating Table [dbo].[Companies]...';


GO
CREATE TABLE [dbo].[Companies] (
    [Id]            INT          NOT NULL,
    [Code]          VARCHAR (20) NOT NULL,
    [Description]   VARCHAR (30) NOT NULL,
    [EmployeeCount] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

PRINT N'Creating Table [dbo].[Employeees]...';

CREATE TABLE [dbo].[Employees] (
    [EmployeeNumber]        VARCHAR (10) NOT NULL,
    [FullName]              VARCHAR (40) NOT NULL,
    [Email]                 VARCHAR (40) NOT NULL,
    [Department]            VARCHAR (40) NOT NULL,
    [HireDate]              DATETIME     NULL,
    [ManagerEmployeeNumber] VARCHAR (10) NULL,
    [CompanyId]             INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([EmployeeNumber], [CompanyId] ASC),
    CONSTRAINT [FK_Companies_Employees] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([Id])
);

GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
GO
PRINT N'Update complete.';


GO
